### ISSUE TITLE
`use client` is missing

### ISSUE THREAD

**Issue by rovo89** [a16n-dev/react-dialog-async#198]
The [docs](https://react-dialog-async.a16n.dev/concepts/next-js-ssr/) state:
> \<DialogProvider/\> is marked with the 'use client' directive. Simply add it to your app/layout.tsx file and you’re good to go

But no, it's not. In fact, there isn't *any* `use client` in the codebase, apart from the docs. I assume that's why I get this error when importing `DialogOutlet` and `DialogProvider` in my Next.js 15.5 project's `app/layout.tsx`:

```
(0 , __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f$next$2f$dist$2f$server$2f$route$2d$modules$2f$app$2d$page$2f$vendored$2f$rsc$2f$react$2e$js__$5b$app$2d$rsc$5d$__$28$ecmascript$29$__.createContext) is not a function
    at __TURBOPACK__module__evaluation__ (src/app/layout.tsx:13:1)
    at __TURBOPACK__module__evaluation__ (file:///workspaces/playground/.next/server/chunks/ssr/[root-of-the-server]__cf16f9e8._.js:474:47)
    at Object.<anonymous> (.next/server/app/areas/page.js:53:3)
```

Somewhere deep in the stack trace, `IndividualDialogStateContext` was mentioned which indeed uses `createContext()`.

As a workaround, I created a separate file and used the wrapped components:
```tsx
'use client'

// These are workarounds to make react-dialog-async work with Next.js by adding 'use client' to the components.

import { DialogOutlet, DialogProvider } from 'react-dialog-async'

export const DialogProviderWrapper = ({ children }: { children: React.ReactNode }) => {
  return <DialogProvider>{children}</DialogProvider>
}

export const DialogOutletWrapper = () => {
  return <DialogOutlet />
}
```

**Comment by a16n-dev** [comment]
Thanks for flagging this, it looks like it got dropped when the library moved from rollup to tsdown.

I've released a patch that fixes this `3.1.0`

**Comment by rovo89** [comment]
Thanks for the fast fix (again!), however the `<DialogOutlet/>` needs seems to need `use client` as well, I still get the same message if I import it directly from your package. `<DialogProvider>` works fine now.

By the way, the author has changed for the last few commits, probably you used a different email address.

**Comment by rovo89** [comment]
@a16n-dev Sorry for the ping, but I think you missed my answer above and I can't reopen the issue myself.

**Comment by a16n-dev** [comment]
Sorry about that 🤦 I'll get that fixed up

**Comment by a16n-dev** [comment]
Fixed in `3.2.0`, sorry again about the delay there!
